name: Deployment Workflow

on: 
  push:
    branches: [ develop ]

env:
  PROJECT_ROOT: '/var/www/NINA'
  TEST_CONFIG: '/var/.deploy_configs/NINA/test'
    
jobs:
  job_one:
    name: Deploy on dev server
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: |
        npm install
        npm i cross-env
        npm run build
        npm run start:test
        echo "Basic setup tested successfully" && sleep 2
    - name: deploy
      run: |
        npm run build
        npm run start:test
        echo "Basic setup deployed successfully" && sleep 2
          
