name: Deployment Workflow

on: 
  push:
    branches: [ develop ]

env:
  PROJECT_ROOT: /var/www/NINA/
    
jobs:
  job_one:
    name: testing
    env:
      CONFIG: /var/.deploy_configs/NINA/test
    runs-on: ubuntu-latest
    steps:
    - name: testing server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: 13.235.184.34
        username: deploy
        password: YMTV2S6argbp
        port: 22
        script: |
          cd $PROJECT_ROOT
          script:
          npm install
          cp -r $CONFIG/. ./
          npm run build
          npm run start:test
          echo "Basic setup tested successfully" && sleep 2
          
