name: Deployment Workflow

on: 
  push:
    branches: [ develop ]

env:
  PROJECT_ROOT: '/var/www/NINA'
  TEST_CONFIG: '/var/.deploy_configs/NINA/test'
    
jobs:
  job_one:
    name: testing
    runs-on: nina-project-runner
    steps:
    - uses: actions/checkout@v3
    - name: testing server ssh connection
      run: |
        npm install
        npm run build
        npm run start:test
        echo "Basic setup tested successfully" && sleep 2
          
